# Generated by Django 4.1.7 on 2023-02-17 06:39

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('altitude', models.FloatField(null=True)),
                ('ebikes', models.IntegerField(null=True)),
                ('has_ebikes', models.BooleanField(default=True)),
                ('last_updated', models.IntegerField(null=True)),
                ('normal_bikes', models.IntegerField(null=True)),
                ('payment', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('payment_terminal', models.BooleanField(default=True)),
                ('post_code', models.CharField(max_length=255)),
                ('renting', models.IntegerField(null=True)),
                ('returning', models.IntegerField(null=True)),
                ('slots', models.IntegerField(null=True)),
                ('uid', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('uid',)},
            },
        ),
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empty_slots', models.IntegerField(null=True)),
                ('free_bikes', models.IntegerField(null=True)),
                ('id_api', models.CharField(max_length=255)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('timestamp', models.CharField(max_length=255)),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bike_extra', to='bike.extra')),
            ],
            options={
                'unique_together': {('id_api',)},
            },
        ),
    ]
