[tool.black]
line-length = 100
skip-string-normalization = true
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | env
  | _build
  | buck-out
  | build
  | dist
  | migrations
  | venv
)/
'''