# Generated by Django 4.1.7 on 2023-02-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_table', models.IntegerField(null=True)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('tipologia', models.CharField(max_length=255)),
                ('titular', models.CharField(max_length=255)),
                ('inversion', models.CharField(max_length=255)),
                ('fecha_presentacion', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('id_table',)},
            },
        ),
    ]
