# Generated by Django 4.1.7 on 2023-02-19 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion_ambiental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='nombre',
            field=models.CharField(max_length=2550),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='titular',
            field=models.CharField(max_length=2550),
        ),
    ]
